### ISSUE TITLE
Change Scryfall symbols to use `<abbr>` and inline the SVG files to CSS

### ISSUE THREAD

**Issue by xremming** [xremming/rulesraker#1]
Show inline symbols same way as Scryfall does.

---

Scryfall uses the following markup to show symbols, consider using that as a basis.

```html
<abbr class="card-symbol card-symbol-2" title="two generic mana">{2}</abbr>
```

```css
.card-symbol-2 {
  background-image: url(data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy...);
}

.card-symbol {
  display: inline-block;
  margin: 1px 1px -1px 1px;
  -webkit-border-radius: 500px;
  border-radius: 500px;
  -webkit-box-shadow: -1px 1px 0 rgba(0,0,0,0.85);
  box-shadow: -1px 1px 0 rgba(0,0,0,0.85);
  text-indent: -999em;
  overflow: hidden;
  width: 15px;
  height: 15px;
  -webkit-background-size: 100% 100%;
  background-size: 100% 100%;
  background-position: top left;
  -webkit-print-color-adjust: exact;
  color-adjust: exact;
  print-color-adjust: exact;
  cursor: help;
}
```
